export const EXPRESSION_CATEGORIES = [
  {
    id: 'opinion',
    label: '의견 표현',
    color: 'blue',
    expressions: [
      { id: 'op1', en: 'In my opinion, ...', ko: '가장 무난한 의견 시작 표현' },
      { id: 'op2', en: 'From my perspective, ...', ko: '나의 관점에서 — 격식체' },
      { id: 'op3', en: 'Personally, I believe that ...', ko: '개인적 의견을 강조할 때' },
      { id: 'op4', en: 'I strongly feel that ...', ko: '강한 확신을 전달할 때' },
      { id: 'op5', en: "As far as I'm concerned, ...", ko: '자신의 판단임을 명확히 할 때' },
      { id: 'op6', en: "I'm convinced that ...", ko: '확고한 신념 표현' },
      { id: 'op7', en: 'It is my view that ...', ko: '공식적·격식체 의견 표현' },
    ],
  },
  {
    id: 'reason',
    label: '이유·원인',
    color: 'green',
    expressions: [
      { id: 're1', en: 'This is because ...', ko: '이유를 직접 설명할 때' },
      { id: 're2', en: 'The main reason for this is ...', ko: '핵심 이유를 강조할 때' },
      { id: 're3', en: 'One key factor is ...', ko: '여러 이유 중 하나를 꼽을 때' },
      { id: 're4', en: 'This can be attributed to ...', ko: '원인을 ~에 돌릴 때 (격식체)' },
      { id: 're5', en: 'What makes this significant is ...', ko: '왜 중요한지 설명할 때' },
      { id: 're6', en: 'This leads to ...', ko: '원인이 결과로 이어질 때' },
    ],
  },
  {
    id: 'example',
    label: '예시 들기',
    color: 'amber',
    expressions: [
      { id: 'ex1', en: 'For example, ...', ko: '가장 일반적인 예시 표현' },
      { id: 'ex2', en: 'For instance, ...', ko: 'for example의 격식 대체어' },
      { id: 'ex3', en: 'A good example of this is ...', ko: '예시를 강조해서 들 때' },
      { id: 'ex4', en: 'To illustrate, ...', ko: '설명을 위한 예시를 들 때' },
      { id: 'ex5', en: 'Take ... as an example.', ko: '특정 대상을 예시로 지목할 때' },
      { id: 'ex6', en: 'This can be seen in ...', ko: '예시를 통해 증명할 때' },
    ],
  },
  {
    id: 'addition',
    label: '추가·강조',
    color: 'purple',
    expressions: [
      { id: 'ad1', en: 'Furthermore, ...', ko: '더 중요한 내용을 덧붙일 때' },
      { id: 'ad2', en: 'In addition, ...', ko: '무난하게 내용을 추가할 때' },
      { id: 'ad3', en: 'Moreover, ...', ko: '앞 내용보다 강한 포인트를 추가' },
      { id: 'ad4', en: "What's more, ...", ko: '구어체로 추가 강조' },
      { id: 'ad5', en: 'On top of that, ...', ko: '이미 좋은/나쁜 상황에 더해서' },
      { id: 'ad6', en: 'Not only that, but ...', ko: '앞 내용을 포함해 더 강조' },
    ],
  },
  {
    id: 'contrast',
    label: '대조·반전',
    color: 'red',
    expressions: [
      { id: 'ct1', en: 'However, ...', ko: '가장 일반적인 역접 표현' },
      { id: 'ct2', en: 'On the other hand, ...', ko: '대조되는 관점을 제시할 때' },
      { id: 'ct3', en: 'That said, ...', ko: '앞 내용을 인정하면서 반전할 때' },
      { id: 'ct4', en: 'Despite this, ...', ko: '~에도 불구하고 (격식체)' },
      { id: 'ct5', en: 'Even so, ...', ko: '그럼에도 불구하고 (구어체)' },
      { id: 'ct6', en: 'In contrast, ...', ko: '뚜렷하게 대비할 때' },
      { id: 'ct7', en: 'While [A], [B].', ko: 'A와 B를 한 문장에서 대조' },
    ],
  },
  {
    id: 'concession',
    label: '양보·반론 인정',
    color: 'orange',
    expressions: [
      { id: 'co1', en: "While I understand that ..., I still believe ...", ko: '상대방 입장 인정 후 내 의견 유지' },
      { id: 'co2', en: 'Admittedly, ... However, ...', ko: '솔직히 인정하지만 반론' },
      { id: 'co3', en: "It's true that ..., but ...", ko: '~가 사실이지만 그래도' },
      { id: 'co4', en: 'Although some might argue that ..., ...', ko: '반대 의견을 인용 후 반박' },
      { id: 'co5', en: 'Of course, ... but ...', ko: '물론 그렇지만 — 구어체 양보' },
    ],
  },
  {
    id: 'conclusion',
    label: '결론·마무리',
    color: 'gray',
    expressions: [
      { id: 'cl1', en: 'Therefore, ...', ko: '논리적 결론을 이끌 때' },
      { id: 'cl2', en: 'All things considered, ...', ko: '모든 점을 고려했을 때' },
      { id: 'cl3', en: 'For these reasons, I believe ...', ko: 'Part 6 마무리에 최적' },
      { id: 'cl4', en: 'Ultimately, ...', ko: '결국 가장 중요한 점은' },
      { id: 'cl5', en: 'In the long run, ...', ko: '장기적으로 봤을 때' },
      { id: 'cl6', en: 'Overall, I think ...', ko: '전반적으로 내 생각은' },
      { id: 'cl7', en: 'The advantages far outweigh the disadvantages.', ko: '장점이 단점을 크게 앞선다 — Part 6 단골' },
    ],
  },
  {
    id: 'recommend',
    label: '추천·제안',
    color: 'teal',
    expressions: [
      { id: 'rc1', en: 'I would recommend ...', ko: 'Part 4 Q10 추천 답변에 최적' },
      { id: 'rc2', en: 'I suggest that ...', ko: '제안할 때 (that + 주어 + 동사원형)' },
      { id: 'rc3', en: 'It might be a good idea to ...', ko: '부드럽게 제안할 때' },
      { id: 'rc4', en: 'If I were you, I would ...', ko: '가정법으로 조언할 때' },
      { id: 'rc5', en: 'One option would be to ...', ko: 'Part 5 해결책 제시 표현' },
      { id: 'rc6', en: 'Alternatively, ...', ko: '또 다른 대안을 제시할 때' },
    ],
  },
  {
    id: 'part5',
    label: 'Part 5 전용',
    color: 'pink',
    expressions: [
      { id: 'p5e1', en: 'I completely understand your situation.', ko: '상대방 공감 — 반드시 먼저 나와야 함' },
      { id: 'p5e2', en: 'I sincerely apologize for the inconvenience.', ko: '격식 있는 사과 표현' },
      { id: 'p5e3', en: 'I have a couple of suggestions.', ko: '해결책 2개 제시 예고 → First / Alternatively' },
      { id: 'p5e4', en: "I'll look into this right away and get back to you.", ko: '즉시 처리 약속' },
      { id: 'p5e5', en: "To make up for this, I'd like to offer you ...", ko: '보상 제안 표현' },
      { id: 'p5e6', en: "Please don't hesitate to contact me if ...", ko: '마무리 문장 — 연락처 언급 후 사용' },
      { id: 'p5e7', en: "I've already contacted [department] and confirmed that ...", ko: '조치 완료 보고 — 신뢰감 UP' },
      { id: 'p5e8', en: 'You can reach me at ...', ko: '연락처 안내 마무리' },
    ],
  },
  {
    id: 'part2',
    label: 'Part 2 전용',
    color: 'cyan',
    expressions: [
      { id: 'p2e1', en: 'This picture appears to show ...', ko: '사진 묘사 시작 — 가장 안전한 표현' },
      { id: 'p2e2', en: 'In the foreground / background, ...', ko: '전경·배경 구분해서 묘사' },
      { id: 'p2e3', en: 'On the left / right side of the picture, ...', ko: '위치를 명확히 묘사' },
      { id: 'p2e4', en: '[Someone] appears to be -ing ...', ko: '행동 추측 — 단정 대신 추측으로 안전하게' },
      { id: 'p2e5', en: 'It looks like ...', ko: '외관상 ~처럼 보임 (구어체)' },
      { id: 'p2e6', en: 'The overall atmosphere appears to be ...', ko: '분위기 묘사 마무리에 유용' },
      { id: 'p2e7', en: 'What stands out to me is ...', ko: '눈에 띄는 요소를 강조할 때' },
      { id: 'p2e8', en: 'In the center of the image, ...', ko: '중앙 요소 묘사' },
    ],
  },
  {
    id: 'filler',
    label: '시간 벌기',
    color: 'lime',
    expressions: [
      { id: 'fi1', en: 'Well, to be honest, ...', ko: '자연스럽게 시작하면서 1~2초 확보' },
      { id: 'fi2', en: "That's actually a really interesting question.", ko: '생각할 시간 확보 — 남용 금지, 1회만' },
      { id: 'fi3', en: 'What I mean is ...', ko: '앞 말을 보완·수정할 때' },
      { id: 'fi4', en: 'To be more specific, ...', ko: '구체적으로 말하자면 — 내용을 확장' },
      { id: 'fi5', en: 'Let me put it this way — ...', ko: '다른 방식으로 설명할 때' },
    ],
  },
]

export const COLOR_MAP = {
  blue:   { chip: 'bg-blue-100 text-blue-700',   border: 'border-blue-200',  dot: 'bg-blue-400' },
  green:  { chip: 'bg-green-100 text-green-700',  border: 'border-green-200', dot: 'bg-green-400' },
  amber:  { chip: 'bg-amber-100 text-amber-700',  border: 'border-amber-200', dot: 'bg-amber-400' },
  purple: { chip: 'bg-purple-100 text-purple-700', border: 'border-purple-200', dot: 'bg-purple-400' },
  red:    { chip: 'bg-red-100 text-red-700',      border: 'border-red-200',   dot: 'bg-red-400' },
  orange: { chip: 'bg-orange-100 text-orange-700', border: 'border-orange-200', dot: 'bg-orange-400' },
  gray:   { chip: 'bg-gray-100 text-gray-600',    border: 'border-gray-200',  dot: 'bg-gray-400' },
  teal:   { chip: 'bg-teal-100 text-teal-700',    border: 'border-teal-200',  dot: 'bg-teal-400' },
  pink:   { chip: 'bg-pink-100 text-pink-700',    border: 'border-pink-200',  dot: 'bg-pink-400' },
  cyan:   { chip: 'bg-cyan-100 text-cyan-700',    border: 'border-cyan-200',  dot: 'bg-cyan-400' },
  lime:   { chip: 'bg-lime-100 text-lime-700',    border: 'border-lime-200',  dot: 'bg-lime-400' },
}
